const Map<String, String> _flagsByCountry = {
  'Russia': '🇷🇺',
  'Brazil': '🇧🇷',
  'France': '🇫🇷',
  'Kazakhstan': '🇰🇿',
  'Bosnia and Herzegovina': '🇧🇦',
  'Israel': '🇮🇱',
  'Ukraine': '🇺🇦',
  'Belarus': '🇧🇾',
  'Slovakia': '🇸🇰',
  'Lithuania': '🇱🇹',
  'Hungary': '🇭🇺',
  'Poland': '🇵🇱',
  'Latvia': '🇱🇻',
  'Canada': '🇨🇦',
  'Mongolia': '🇲🇳',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'United Kingdom': '🇬🇧',
  'Bulgaria': '🇧🇬',
  'Uruguay': '🇺🇾',
  'Romania': '🇷🇴',
  'Sweden': '🇸🇪',
  'Czech Republic': '🇨🇿',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Kosovo': '🇽🇰',
  'Estonia': '🇪🇪',
  'Spain': '🇪🇸',
  'Türkiye': '🇹🇷',
  'Turkey': '🇹🇷',
  'Germany': '🇩🇪',
  'Netherlands': '🇳🇱',
  'Portugal': '🇵🇹',
  'United States': '🇺🇸',
  'Australia': '🇦🇺',
  'Norway': '🇳🇴',
  'Switzerland': '🇨🇭',
  'Belgium': '🇧🇪',
  'Italy': '🇮🇹',
  'Slovenia': '🇸🇮',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Austria': '🇦🇹',
  'Greece': '🇬🇷',
  'Saudi Arabia': '🇸🇦',
};

String countryFlag(String? country) {
  if (country == null) return '';
  return _flagsByCountry[country] ?? '';
}
